version: "3.9"
services:
  db:
    image: postgres:16
    environment: { POSTGRES_PASSWORD: lamp }
    ports: ["5432:5432"]

  product:
    build: ./product-service
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:lamp@db:5432/postgres"
    depends_on: [db]
    ports: ["8001:80"]

  order:
    build: ./order-service
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:lamp@db:5432/postgres"
    depends_on: [db]
    ports: ["8002:80"]
